version: "3.9"
services:
  backend:
    build: .
    working_dir: /backend/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes: 
      - ./backend:/backend/app
    ports:
      - "8000:8000"